"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Activity, Shield, Map, Save, Code2, Sliders,
  MessageCircle, GitCompare, Vote, Mail,
  DollarSign, GitBranch, Layers, Github, FileText, Users,
} from "lucide-react";
import type { GenResult } from "@/lib/api/client";

import MetricsPanel from "./MetricsPanel";
import SecurityPanel from "./SecurityPanel";
import RoadmapPanel from "./RoadmapPanel";
import SaveSharePanel from "./SaveSharePanel";
import APISpec from "./APISpec";
import WhatIfSimulator from "./WhatIfSimulator";
import ArchChat from "./ArchChat";
import CompareArchitectures from "./CompareArchitectures";
import DecisionVoting from "./DecisionVoting";
import CostCalculator from "./CostCalculator";
import DataFlowDiagram from "./DataFlowDiagram";
import TechStackDeepDive from "./TechStackDeepDive";
import GitHubIssuesExport from "./GitHubIssuesExport";
import { ADRGenerator } from "./ADRAndTeam";
import { TeamStructure } from "./ADRAndTeam";

interface P { result: GenResult; tab: ExtraTab; }

export type ExtraTab =
  | "metrics" | "security" | "roadmap" | "save"
  | "api" | "whatif" | "chat" | "compare" | "decisions" | "email"
  | "cost" | "dataflow" | "techdeep" | "issues" | "adrs" | "team";

export const EXTRA_TABS: { id: ExtraTab; label: string; icon: React.ElementType; group: string; badge?: string }[] = [
  // Understand
  { id: "metrics", label: "Metrics", icon: Activity, group: "Understand" },
  { id: "security", label: "Security", icon: Shield, group: "Understand" },
  { id: "cost", label: "Cost", icon: DollarSign, group: "Understand" },
  { id: "dataflow", label: "Data Flow", icon: GitBranch, group: "Understand" },
  { id: "techdeep", label: "Tech Deep", icon: Layers, group: "Understand" },
  // Build
  { id: "api", label: "API Spec", icon: Code2, group: "Build" },
  { id: "roadmap", label: "Roadmap", icon: Map, group: "Build" },
  // { id: "whatif",   label: "What-if",    icon: Sliders,      group: "Build"      },
  // { id: "chat",     label: "Ask AI",     icon: MessageCircle,group: "Build", badge: "AI" },
  // Team
  // { id: "issues",   label: "GH Issues",  icon: Github,       group: "Team"       },
  // { id: "adrs",     label: "ADRs",       icon: FileText,     group: "Team"       },
  // { id: "team",     label: "Team",       icon: Users,        group: "Team"       },
  // { id: "decisions",label: "Decisions",  icon: Vote,         group: "Team"       },
  // Export
  // { id: "compare",  label: "Compare",    icon: GitCompare,   group: "Export"     },
  { id: "email", label: "Email", icon: Mail, group: "Export" },
  { id: "save", label: "Save", icon: Save, group: "Export" },
];

// ── Email Panel (inline — small enough) ────────────────────────────────────
function EmailPanel({ result }: { result: GenResult }) {
  const [sent, setSent] = useState(false);
  const bp = result.blueprint;
  const req = result.requirements;

  const subject = encodeURIComponent(
    `Architecture Blueprint: ${bp.architecture_pattern?.replace(/_/g, " ")} — ${new Date().toLocaleDateString()}`
  );
  const body = encodeURIComponent(
    `Architecture Blueprint — Generated by Scaff

Pattern: ${bp.architecture_pattern?.replace(/_/g, " ")}
Deployment: ${bp.deployment_model?.replace(/_/g, " ")}
Target Users: ${req.user_scale?.target?.toLocaleString()}
Availability: ${req.availability_sla_percent}%

STACK
Primary DB: ${bp.primary_db || "—"}
Cache: ${bp.cache || "—"}
Search: ${bp.search_engine || "—"}
Queue: ${bp.message_bus || "—"}

SERVICES
${bp.services?.map(s => `• ${s.name}: ${s.responsibility} (${s.tech_stack?.[0]})`).join("\n") || "—"}

COST
Monthly: $${bp.cost_estimate?.monthly_usd_low || "?"}–$${bp.cost_estimate?.monthly_usd_high || "?"}
Driver: ${bp.cost_estimate?.biggest_cost_driver || "compute"}

TRADE-OFFS
${bp.trade_offs?.map(t => `• ${t.decision}\n  Pros: ${t.pros?.join(", ")}\n  Cons: ${t.cons?.join(", ")}`).join("\n\n") || "—"}

---
Generated with Scaff`
  );

  return (
    <div style={{ maxWidth: 520, display: "flex", flexDirection: "column", gap: 14 }}>
      <div style={{ padding: "20px", borderRadius: 14, border: "1px solid rgba(77,158,247,0.2)", background: "rgba(77,158,247,0.05)" }}>
        <p style={{ fontSize: 15, fontWeight: 700, color: "#fff", marginBottom: 8 }}>Email this Blueprint</p>
        <p style={{ fontSize: 12, color: "#9ca3af", lineHeight: 1.6, marginBottom: 16 }}>
          Opens your email client with the full blueprint pre-filled — pattern, stack, services, trade-offs, and cost.
        </p>
        <div style={{ padding: "10px 14px", borderRadius: 9, background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", marginBottom: 14, fontFamily: "'JetBrains Mono',monospace", fontSize: 11, color: "#6b7280", lineHeight: 1.7 }}>
          <p><span style={{ color: "#4d9ef7" }}>Subject:</span> Architecture Blueprint: {bp.architecture_pattern?.replace(/_/g, " ")}</p>
          <p><span style={{ color: "#4d9ef7" }}>Includes:</span> Stack · Services · Trade-offs · Cost · Roadmap</p>
        </div>
        <button onClick={() => { window.open(`mailto:?subject=${subject}&body=${body}`, "_blank"); setSent(true); setTimeout(() => setSent(false), 3000); }}
          style={{
            width: "100%", padding: "12px", borderRadius: 10, cursor: "pointer", fontSize: 13, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, transition: "all 0.2s",
            background: sent ? "rgba(74,222,128,0.1)" : "rgba(77,158,247,0.1)",
            border: `1px solid ${sent ? "rgba(74,222,128,0.3)" : "rgba(77,158,247,0.3)"}`,
            color: sent ? "#4ade80" : "#4d9ef7",
          }}>
          <Mail size={14} /> {sent ? "Email client opened!" : "Open in Email Client"}
        </button>
      </div>
      <p style={{ fontSize: 11, color: "#374151", textAlign: "center" }}>Uses mailto: · works with Gmail, Outlook, Apple Mail</p>
    </div>
  );
}

// ── Main ───────────────────────────────────────────────────────────────────
export default function ExtraFeatures({ result, tab }: P) {
  return (
    <AnimatePresence mode="wait">
      <motion.div key={tab}
        initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0 }} transition={{ duration: 0.18 }}>
        {tab === "metrics" && <MetricsPanel result={result} />}
        {tab === "security" && <SecurityPanel result={result} />}
        {tab === "roadmap" && <RoadmapPanel result={result} />}
        {tab === "save" && <SaveSharePanel result={result} />}
        {tab === "api" && <APISpec result={result} />}
        {tab === "whatif" && <WhatIfSimulator result={result} />}
        {tab === "chat" && <ArchChat result={result} />}
        {tab === "compare" && <CompareArchitectures result={result} />}
        {tab === "decisions" && <DecisionVoting result={result} />}
        {tab === "email" && <EmailPanel result={result} />}
        {tab === "cost" && <CostCalculator result={result} />}
        {tab === "dataflow" && <DataFlowDiagram result={result} />}
        {tab === "techdeep" && <TechStackDeepDive result={result} />}
        {tab === "issues" && <GitHubIssuesExport result={result} />}
        {tab === "adrs" && <ADRGenerator result={result} />}
        {tab === "team" && <TeamStructure result={result} />}
      </motion.div>
    </AnimatePresence>
  );
}
